version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app    # Mount the backend code
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  # Uncomment the db service and the volumes section when you are ready to use MongoDB
  # db:
  #   image: mongo:4.4
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db

# Uncomment the volumes section when you are ready to use MongoDB
# volumes:
#   mongo_data:
